# fly.toml - Discord Bot (FREE SAFE)

app = "discord-bot-autumn-morning-5147"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[deploy]
  strategy = "rolling"
  release_command = "npx prisma migrate deploy"

[processes]
  app = "npm run start"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
